In [71]:
class Point:
    def __init__(self,a,b):
        self.a=int(a)
        self.b=int(b)
    def show(self):
        a=int(self.a)
        b=int(self.b)
        print((a,b))
a=Point(1,2)
a.show()
b=Point(3,4)
b.show()


(1, 2)
(3, 4)


In [34]:
import csv
f=open('seoul.csv')
data=csv.reader(f)
next(data)
result1=0
result2=0
result3=0
result4=0
result5=0
result=[]
max=0
max_num=0
for row in data:
    if (row[0].split('-')[2]<'08'):
        a=float(row[4])-float(row[3])
        result1+=a
    if (row[0].split('-')[2]>'07' and row[0].split('-')[2]<'15'):
        a=float(row[4])-float(row[3])
        result2+=a
    if (row[0].split('-')[2]>'14' and row[0].split('-')[2]<'22'):
        a=float(row[4])-float(row[3])
        result3+=a
    if (row[0].split('-')[2]>'21' and row[0].split('-')[2]<'29'):
        a=float(row[4])-float(row[3])
        result4+=a
    if (row[0].split('-')[2]>'28'):
        a=float(row[4])-float(row[3])
        result5+=a
result.append(result1)
result.append(result2)
result.append(result3)
result.append(result4)
result.append(result5)
for i in range(0,5):
    if max<result[i]:
        max=result[i]
        max_num=i
if max_num==0:
     print('Max week: 05/01~05/07')
if max_num==1:
     print('Max week: 05/08~05/14')
if max_num==2:
     print('Max week: 05/15~05/21')
if max_num==3:
     print('Max week: 05/21~05/28')
if max_num==4:
     print('Max week: 05/28~05/31')

Max week: 05/08~05/14


In [52]:
import numpy as np
docs=np.array([[1,1,0,1,0,1],[1,1,1,0,1,0],[1,1,0,1,0,0]])
print(docs)

[[1 1 0 1 0 1]
 [1 1 1 0 1 0]
 [1 1 0 1 0 0]]
